name: Run Automation Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
    
jobs:
    build-and-test:
        runs-on: windows-latest
        env:
          SAUCEDEMO_STANDARD_USER: ${{ secrets.SAUCEDEMO_STANDARD_USER }}
          SAUCEDEMO_STANDARD_PASS: ${{ secrets.SAUCEDEMO_STANDARD_PASS }}
          SAUCEDEMO_VISUAL_USER: ${{ secrets.SAUCEDEMO_VISUAL_USER }}
          SAUCEDEMO_VISUAL_PASS: ${{ secrets.SAUCEDEMO_VISUAL_PASS }}
          SAUCEDEMO_LOCKED_USER: ${{ secrets.SAUCEDEMO_LOCKED_USER }}
          SAUCEDEMO_LOCKED_PASS: ${{ secrets.SAUCEDEMO_LOCKED_PASS }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                    dotnet-version: 8.0

            - name: Restore dependencies
              run: dotnet restore
              
            - name: Build Project
              run: dotnet build --no-restore

            - name: Run Tests
              run: dotnet test --no-build

            - name: List logs
              shell: pwsh
              run: |
                Get-ChildItem -Path . -Recurse -Filter *.log | ForEach-Object { $_.FullName }

            - name: List reports
              shell: pwsh
              run: |
                Get-ChildItem -Path . -Recurse -Filter *.html | ForEach-Object { $_.FullName }

            - name: Upload logs
              uses: actions/upload-artifact@v4
              with:
                    name: Test-logs
                    path: "**/logs/*.log"

            - name: Upload Reports
              uses: actions/upload-artifact@v4
              with:
                    name: Test-Reports
                    path: "**/Reports/*.html"