name: Run Automation Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
    
jobs:
    build-and-test:
        runs-on: windows-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                    dotnet-version: 8.0

            - name: Restore dependencies
              run: dotnet restore
              
            - name: Build Project
              run: dotnet build --no-restore

            - name: Run Tests
              run: dotnet test --no-build

            - name: Upload logs
              uses: actions/upload-artifact@v4
              with:
                    name: Test-logs
                    path: bin/Debug/net8.0/logs/*.log

            - name: Upload Reports
              uses: actions/upload-artifact@v4
              with:
                    name: Test-Reports
                    path: bin/Debug/net8.0/Reports/*.html